PassageCraft: "Developed by MeshCollider"
MaxPlayers: 16
MinPlayers: 1
JoinMessage: "You have joined the map [MAPNAME], Good Luck!"
QuitMessage: "You have succesfully left the map"
PublicJoinMessage: "[PLAYER] has joined the map [MAPNAME]"
PublicQuitMessage: "[PLAYER] has quit the map [MAPNAME]"
MapStart: "The map [MAPNAME] has started!"
MapEnd: "The map [MAPNAME] has ended. Congratulations to all winners"
NotJoinedMessage: "You aren't currently in a map"
PublishMessage: "The map [MAPNAME] is now open! join now using /pcjoin [MAPNAME]"
DeleteMessage: "The map [MAPNAME] has been sucessfully deleted"
CreateMessage: "The map [MAPNAME] has been sucessfully created"
LobbyMessage: "The lobby for [MAPNAME] has been sucessfully set"
PlayerSetMessage: "Min and Max players successfully set for the map [MAPNAME]"
HubMessage: "Hub succesfully set!"
SpawnPointMessage: "Spawnpoint [SPAWNNUMBER] set for map [MAPNAME]"
MapNotFoundMessage: "That map does not exist"
AlreadyExistsMessage: "The map [MAPNAME] already exists"
NonPlayerMessage: "This command can only be run by a player"
MapFullMessage: "The map [MAPNAME] is full. Only VIP players can join full maps"
MapInProgressMessage: "The map [MAPNAME] is currently in progress"
SpawnNumberMessage: "Please enter a number between 1 and 4"
NoMapsMessage: "No maps created"
InfoMessage: "Details for the map [MAPNAME]"
KitInfoMessage: "Details for the kit [KITNAME]"
MapBeginTime: 20
MapWaitMessage: "The map [MAPNAME] will begin in 20 seconds"
MapLengthTime: 120
ProtectedBlockMessage: "That block is protected!"
ProtectedBlockBrokenMessage: "You have broken a protected block"
ProtectedAreaMessage: "That area is protected!"
ProtectedBlockPlacedMessage: "You have placed a block in a protected area"
NoKitsMessage: "No available kits"
KitNotFoundMessage: "The kit [KITNAME] was not found"
KitSetMessage: "The kit for map [MAPNAME] is now set to [KITNAME]"
KillMessage: "[PLAYERNAME1] has been stabbed to death by [PLAYERNAME2]"
AlreadyJoinedMessage: "You are currently in map [MAPNAME]"
KillStreakAwards: true
KillStreakAwardMessage: "Congratulations, You have been awarded the killstreak kit!"
KillStreak: 2
KillStreakMessage: "[PLAYER] is now on a killstreak! [KILLSTREAK] kills!"
MapUnavailableMessage: "The map [MAPNAME] is currently unavailable sorry"
NukeroomMessage: "[PLAYER] has made it to the nukeroom of map [MAPNAME]!"
MapReloadTime: 30
MapSurvivedMessage: "Congratulations to [PLAYERS] for surviving the map [MAPNAME]!"
MapKilledMessage: "[PLAYERS] perished in the attempt to survive the nukeroom of [MAPNAME]"
EveryoneSurvivedMessage: "Everyone survived in the nukeroom of [MAPNAME]!"
EveryoneDiedMessage: "Nobody survived the attempt to reach the nukeroom of [MAPNAME]!"
InvincibleInNukeroom: true
KilledNukeroomMessage: "[PLAYER] was killed in the nukeroom of [MAPNAME]"
EmptyMapMessage: "Everybody has left the map [MAPNAME]"
CheckpointMessage: "You have succesfully reached a checkpoint!"
SignColourFirstLine: "§2"
SignColourSecondLine: "§1"
SignColourThirdLine: "§5"
SignColourFourthLine: "§5"
CheckpointSignColour: "§6"
Lightning: true
Traps: true
ErrorColour: "§C"
CreateColour: "§A"
PublishColour: "§E"
InfoColour: "§B"